### PR TITLE
Another test case

### PR DESCRIPTION
**Pull request by kesterlester**

### CODE REVIEW

**Comment by kesterlester** [comment]
You can probably change the test value to 0.09719971 and then get rid of the rel keyword and its argument.  In fact you may have to do so to get the test to pass.

**Comment by tpgillam** [comment]
Can you check that it passes please, and perform this update if required? Once you have it checked out locally you should be able to do:

`python setup.py test`

to run the tests.

**Comment by kesterlester** [comment]
I checked last night that it passes if you replace the thing with  0.09719971

**Comment by kesterlester** [comment]
I.e. replace last line with:

`assert computed_val == pytest.approx(0.09719971)`

**Comment by kesterlester** [comment]
PS - I have tried running the test locally, but can't get it to work for a different reason than the test being bad:

```running pytest
running egg_info
writing mt2.egg-info/PKG-INFO
writing requirements to mt2.egg-info/requires.txt
writing dependency_links to mt2.egg-info/dependency_links.txt
writing top-level names to mt2.egg-info/top_level.txt
reading manifest file 'mt2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
/Users/lester/LESTERHOME/proj/bitbucket/mt2-PiPI/.eggs/pytest_runner-5.2-py3.5.egg/ptr.py:187: UserWarning: pytest-runner will stop working on this version of setuptools; please upgrade to setuptools 30.4 or later or pin to pytest-runner < 5.
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'mt2.egg-info/SOURCES.txt'
running build_ext
building '_mt2' extension
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DVERSION_INFO=0.1.5 -DENABLE_INLINING=1 -DDISABLE_COPYRIGHT_PRINTING=1 -I/Users/lester/python-virtual-environments/p3.5/lib/python3.5/site-packages/numpy/core/include -I/Users/lester/python-virtual-environments/p3.5/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c src/main.cpp -o build/temp.macosx-10.15-x86_64-3.5/src/main.o
In file included from src/main.cpp:2:
In file included from /Users/lester/python-virtual-environments/p3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
/Users/lester/python-virtual-environments/p3.5/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
src/main.cpp:80:37: error: cannot initialize an array element of type 'PyUFuncGenericFunction' (aka 'void (*)(char **, long *, long *, void *)') with an rvalue of type 'void (*)(char **, const npy_intp *, const npy_intp *, void *)' (aka 'void (*)(char **, const long *, const long *, void *)'): type mismatch at 2nd parameter ('npy_intp *' (aka 'long *') vs 'const npy_intp *' (aka 'const long *'))
PyUFuncGenericFunction ufuncs[1] = {&mt2_ufunc};
                                    ^~~~~~~~~~
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

**Comment by kesterlester** [comment]
Ohh. Finally a NICE feature of github. When I pushed the change to the patch-4 branch, this whole thread automatically decided I'd want the pull-request to be modified, and it was updated without me having to request it. That's a nice feature.

**Comment by tpgillam** [comment]
Aha! That's interesting. I think this failure mode is caused by your version of numpy being too old -- at some point the second and third arguments went from having to be `long*` to `const long*`. The latter is definitely more correct, but the documentation still used the former.

Can you create an issue for this please, ideally with the version of numpy that you're having problems with? I reckon there'll be some kind of macro switch I can insert to support both. Thanks!

**Comment by kesterlester** [comment]
It’s  also failing on the CI site due to a numpy coplaint.

Isn’t it better to get the CI site configuration working — it looks like it could do a good job of testing these patches if it new how to require numpy:

**Comment by kesterlester** [comment]
Oops, my image was not uploaded to show the CI problem. Here it is:

image

**Comment by tpgillam** [comment]
I've already made an issue about the CI. This is an unrelated issue. Would be great if discussion on problems could be done with the issue tracker please... otherwise I'm really struggling to keep track. Thanks!

**Comment by kesterlester** [comment]
This discussion is all on the tracker.  I see all the last emails, and this one, there. Do you not see them there?

**Comment by tpgillam** [comment]
This discussion here is all on a merge request to do with adding a test case, which is not the right place :-)

**Comment by tpgillam** [comment]
(i.e., please fill out here: https://github.com/tpgillam/mt2/issues/new since this then serves as a TODO list for me, and keeps different unrelated things to fix separated)

**Comment by tpgillam** [comment]
(I'll assume for now that this *should* pass, and will merge. Seems simple enough to fix later if it does not)

**Comment by tpgillam** [comment]
The test does indeed pass for me :-) thanks!

**Pull request merged**
