### PR TITLE
build: put python source in src/mt2 to avoid import confusion

### PR DESCRIPTION
**Pull request by lgray**
Fixes more little issues that came up in #55.

This makes it so cibuildwheel automatically checks that the wheel is correctly formed and installs correctly.

### CODE REVIEW

**Comment by lgray** [comment]
Yep, there we go. 
@tpgillam good to go now with a small organizational change.

**Comment by lgray** [comment]
@henryiii what's the correct invocation to pick up the mt2 package in this case? If I try `include = ["src/mt2*"]` then it fails when running tests from actions inside the uv sync venv. 

I can reproduce this on my laptop but it's not exactly clear what's going wrong.

**Comment by lgray** [comment]
Ah, nevermind. Read the manual. :-)

**Comment by lgray** [comment]
@tpgillam I'm happy to back out the second commit I've added. It makes `_mt2` a sub-package of `mt2`, which is a common practice. It has an added side effect that the build shared object libraries stay within wherever `mt2` is installed, which is pleasantly clean.

**Comment by tpgillam** [comment]
Thanks @lgray ! Looks good - can you have a look at https://github.com/lgray/mt2/pull/2 please? It's a "review" into this branch with a few other teaks, and bumping the version to 1.2.2 .

**Review by tpgillam — APPROVED** [review]

**Pull request merged**
